version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "test"
    ports:
      - "15672:15672"
      - "5672:5672"
    # volumes:
    #   - ./config.json:/etc/rabbitmq/rabbitmq.config
